config/routes.rb
Rails.application.routes.draw do
  resources :applied_jobs
  resources :companies
  resources :employees
  resources :jobs
  resources :employesses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
end

app/controllers/applied_jobs_controller.rb
class AppliedJobsController < ApplicationController
  before_action :set_applied_job, only: [:show, :edit, :update, :destroy]

  # GET /applied_jobs
  # GET /applied_jobs.json
  def index
    @applied_jobs = AppliedJob.all
  end

  # GET /applied_jobs/1
  # GET /applied_jobs/1.json
  def show
  end

  # GET /applied_jobs/new
  def new
    @applied_job = AppliedJob.new
  end

  # GET /applied_jobs/1/edit
  def edit
  end

  # POST /applied_jobs
  # POST /applied_jobs.json
  def create
    @applied_job = AppliedJob.new(applied_job_params)

    respond_to do |format|
      if @applied_job.save
        format.html { redirect_to @applied_job, notice: 'Applied job was successfully created.' }
        format.json { render :show, status: :created, location: @applied_job }
      else
        format.html { render :new }
        format.json { render json: @applied_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applied_jobs/1
  # PATCH/PUT /applied_jobs/1.json
  def update
    respond_to do |format|
      if @applied_job.update(applied_job_params)
        format.html { redirect_to @applied_job, notice: 'Applied job was successfully updated.' }
        format.json { render :show, status: :ok, location: @applied_job }
      else
        format.html { render :edit }
        format.json { render json: @applied_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_jobs/1
  # DELETE /applied_jobs/1.json
  def destroy
    @applied_job.destroy
    respond_to do |format|
      format.html { redirect_to applied_jobs_url, notice: 'Applied job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applied_job
      @applied_job = AppliedJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applied_job_params
      params.require(:applied_job).permit(:id_employee, :id_company, :id_vacancy)
    end
end

app/helpers/applied_jobs_helper.rb
module AppliedJobsHelper
end

app/views/applied_jobs/_form.html.erb
<%= form_for(applied_job) do |f| %>
  <% if applied_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applied_job.errors.count, "error") %> prohibited this applied_job from being saved:</h2>

      <ul>
      <% applied_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_employee %>
    <%= f.number_field :id_employee %>
  </div>

  <div class="field">
    <%= f.label :id_company %>
    <%= f.number_field :id_company %>
  </div>

  <div class="field">
    <%= f.label :id_vacancy %>
    <%= f.number_field :id_vacancy %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applied_jobs/edit.html.erb
<h1>Editing Applied Job</h1>

<%= render 'form', applied_job: @applied_job %>

<%= link_to 'Show', @applied_job %> |
<%= link_to 'Back', applied_jobs_path %>

app/views/applied_jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applied Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Id employee</th>
      <th>Id company</th>
      <th>Id vacancy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applied_jobs.each do |applied_job| %>
      <tr>
        <td><%= applied_job.id_employee %></td>
        <td><%= applied_job.id_company %></td>
        <td><%= applied_job.id_vacancy %></td>
        <td><%= link_to 'Show', applied_job %></td>
        <td><%= link_to 'Edit', edit_applied_job_path(applied_job) %></td>
        <td><%= link_to 'Destroy', applied_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applied Job', new_applied_job_path %>

app/views/applied_jobs/new.html.erb
<h1>New Applied Job</h1>

<%= render 'form', applied_job: @applied_job %>

<%= link_to 'Back', applied_jobs_path %>

app/views/applied_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id employee:</strong>
  <%= @applied_job.id_employee %>
</p>

<p>
  <strong>Id company:</strong>
  <%= @applied_job.id_company %>
</p>

<p>
  <strong>Id vacancy:</strong>
  <%= @applied_job.id_vacancy %>
</p>

<%= link_to 'Edit', edit_applied_job_path(@applied_job) %> |
<%= link_to 'Back', applied_jobs_path %>